### PR TITLE
Add setup to download test data from Zenodo

### PR DESCRIPTION
**Pull request by jluethi**
- [x] Configure test coverage measurements correctly
- [x] Pooch download setup to use the test datasets
- [x]  Integrate those test datasets in the test setup

### CODE REVIEW

**Comment by jluethi** [comment]
Ok, I'm giving up on making the coverage comment action work... 🤷🏻‍♂️ The tests run, we'd currently have 94% coverage. If anyone wants to figure out on how to make the coverage action work, great. Otherwise, at least we have CI testing.

**Comment by jluethi** [comment]
What this PR now actually brings:
The test data from @nrepina is integrated (see https://github.com/m-albert/fractal-ome-zarr-hcs-stitching/issues/4). 

On the search-first data, the task is working very well!

For 2D data:
Pre registration:
search_first_2d_pre_reg

After registration:
search_first_2d_reg


For 3D data:
Pre registration:
search_first_3d_pre_reg

After registration:
search_first_3d_reg

-----

The task _runs_ on grid data. But the parameters don't appear optimal and we may need some of the work in https://github.com/m-albert/fractal-ome-zarr-hcs-stitching/issues/9 to improve that. The registration does something, but it's not perfect

Pre-Registration:
grid_data_pre_reg


After Registration:
grid_data_reg

That test case is available in `test_stitching_grid.py` and we can use it to validate whether new developments in #9 have the desired effect :)

**Comment by jluethi** [comment]
@m-albert I suggest we remove the old test case and rely on those new test cases. See commit https://github.com/m-albert/fractal-ome-zarr-hcs-stitching/pull/15/commits/15b940106966aa79a67a368133969e951d89985d that removes that old test. If you see use in keeping it, let's revert that one commit and add the test back.

Besides that, this PR is ready to be merged whenever you have a chance to review & merge

**Comment by jluethi** [comment]
Also, if you want to see current coverage, go on the action page. It does display it there:
https://github.com/m-albert/fractal-ome-zarr-hcs-stitching/actions/runs/10113484152

Screenshot 2024-07-26 at 17 18 05

**Review by m-albert — APPROVED** [review]
This is amazing, all these test cases are super useful and it's great to have them integrated into automated testing. This will be super useful for validating progress and preventing regressions.

Code looks all good to me. Great work 🎉, merging now.

**Pull request merged**
