### PR TITLE
[WIP] Metadata & Fractal improvements

### PR DESCRIPTION
**Pull request by jluethi**
This is a WIP PR with updates I've been working on for the fractal multiview stitcher task.

Issues I plan to tackle / have tackled:

- [ ]  Omero metadata: Core Omero metadata is in place, but 2 issues remain
    1. wavelength_id? Not a standard omero key and thus gets ignored with ome-zarr-py writing of omero metadata
    2. **Why does channel order get inverted in the fused zarr??**
- [x]  Placement of output OME-Zarr image
- [x]  Option to delete old image
- [x]  Telling Fractal server about the new image
- [x]  Update to newer fractal-tasks-core version
- [x]  Copy over & adjust ROI tables? Create at least a whole well ROI table
- [x]  Figure out why orginal num_levels fails: 4 works, 5 fails
- [ ]  Test whether logger is working: Doesn't log to console when importing the Python function. Does it work in a Fractal context?
- [x] Update the manifest to handle new task arguments
- [x] Update the manifest to have input & output types
- [ ] Make well metadata update more flexible: 
     - [x] Don't assume well is present (currently makes tests fail)
     - [x] Allow overwrite of existing output in well metadata

Testing required:

- [ ] Also test with 3D data
- [ ] Add specific tests? Is public test data relevant for this?

Issues not tackled by this PR:

- 3D fusion artefacts described by @nrepina: it seems that each saved slice is some sort of projection of a few z-slices
- Semaphore issues @nrepina hit locally (currently can't reproduce those)

### CODE REVIEW

**Comment by jluethi** [comment]
To do before merge:

- [ ] wavelength_id
- [ ] Figure out why orginal num_levels fails: 4 works, 5 fails

**Comment by jluethi** [comment]
@m-albert @nrepina  I also updated the template now and set up the pre-commit configuration. I ran pre-commit once over the whole repo, fixes formatting issues that ruff didn't like and excluded a few ruff rules that seem a bit over the top to me. Let's try to make commits using pre-commit now (running `pre-commit install` in the repo once).

If you can't make sense of a pre-commit issue, you can always circumvent it by using git commit -m "my message" --no-verify

The repo is also set up to use tags for versioning. Once we merge this into main, let's tag that as version 0.0.1. Until we make the first tag, whl building will not work.

**Comment by jluethi** [comment]
@m-albert It's a bit of a messy PR as it touches many parts. But it's complete from my side now. All the open issues still listed above will be tackled elsewhere.

Do you want to have a look and merge when you're happy with it?

**Comment by m-albert** [comment]
@jluethi Thanks for all your work here. Your changes make sense to me and everything looks great 👍

Merging this PR and creating a tag as you suggested.

**Pull request merged**
